module.exports = {
  tt1985949: {
    imdbID: "tt1985949",
    Title: "The Amazing Spider-Man",
    Released: "2012-07-03",
    Runtime: 136,
    Genres: ["Action", "Adventure", "Sci-Fi"],
    Directors: ["Marc Webb"],
    Writers: ["James Vanderbilt", "Alvin Sargent"],
    Actors: ["Andrew Garfield", "Emma Stone", "Rhys Ifans"],
    Plot: "Peter Parker entdeckt seine Kräfte und muss sich als Spider-Man seiner Vergangenheit und dem Echsen-Monster stellen.",
    Poster: "/images/spiderman.jpg",
    Metascore: 66,
    imdbRating: 6.9,
  },
  tt0480249: {
    imdbID: "tt0480249",
    Title: "I Am Legend",
    Released: "2007-12-14",
    Runtime: 101,
    Genres: ["Action", "Drama", "Sci-Fi"],
    Directors: ["Francis Lawrence"],
    Writers: ["Mark Protosevich", "Akiva Goldsman"],
    Actors: ["Will Smith", "Alice Braga", "Charlie Tahan"],
    Plot: "Jahre nachdem ein Virus die Menschheit ausgelöscht hat, kämpft der letzte Überlebende in New York um ein Heilmittel.",
    Poster: "/images/legend.jpg",
    Metascore: 65,
    imdbRating: 7.2,
  },
  tt1111111: {
    imdbID: "tt1111111",
    Title: "The Hangover",
    Released: "2009-06-05",
    Runtime: 100,
    Genres: ["Comedy"],
    Directors: ["Todd Phillips"],
    Writers: ["Jon Lucas", "Scott Moore"],
    Actors: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis"],
    Plot: "Drei Freunde wachen nach einem Junggesellenabschied in Las Vegas auf und können sich an nichts erinnern – und der Bräutigam fehlt.",
    Poster: "/images/hangover.jpg",
    Metascore: 73,
    imdbRating: 7.7,
  },
  tt15239678: {
    imdbID: "tt15239678",
    Title: "Dune: Part Two",
    Released: "2024-03-01",
    Runtime: 166,
    Genres: ["Action", "Adventure", "Sci-Fi"],
    Directors: ["Denis Villeneuve"],
    Writers: ["Denis Villeneuve", "Jon Spaihts"],
    Actors: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    Plot: "Paul Atreides verbündet sich mit Chani und den Fremen, um sich an den Verschwörern zu rächen.",
    Poster: "/images/dune part two.jpg",
    Metascore: 79,
    imdbRating: 8.6,
  },
  tt15327232: {
    imdbID: "tt15327232",
    Title: "Oppenheimer",
    Released: "2023-07-21",
    Runtime: 180,
    Genres: ["Biography", "Drama", "History"],
    Directors: ["Christopher Nolan"],
    Writers: ["Christopher Nolan"],
    Actors: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    Plot: "Die Geschichte des amerikanischen Physikers J. Robert Oppenheimer und seine Rolle bei der Entwicklung der Atombombe.",
    Poster: "/images/oppenheimer.jpg",
    Metascore: 90,
    imdbRating: 8.3,
  },
  tt6263850: {
    imdbID: "tt6263850",
    Title: "Deadpool & Wolverine",
    Released: "2024-07-26",
    Runtime: 128,
    Genres: ["Action", "Comedy", "Sci-Fi"],
    Directors: ["Shawn Levy"],
    Writers: ["Ryan Reynolds", "Rhett Reese"],
    Actors: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
    Plot: "Deadpool muss mit einem widerwilligen Wolverine zusammenarbeiten, um das Universum zu retten.",
    Poster: "/images/deadpool 3.jpg",
    Metascore: 56,
    imdbRating: 7.8,
  },
  tt22022452: {
    imdbID: "tt22022452",
    Title: "Inside Out 2",
    Released: "2024-06-14",
    Runtime: 96,
    Genres: ["Animation", "Adventure", "Comedy"],
    Directors: ["Kelsey Mann"],
    Writers: ["Meg LeFauve"],
    Actors: ["Amy Poehler", "Maya Hawke", "Kensington Tallman"],
    Plot: "Riley ist nun ein Teenager und neue Emotionen wie Zweifel ziehen in die Zentrale ein.",
    Poster: "/images/Inside out 2.jpg",
    Metascore: 73,
    imdbRating: 7.7,
  },
  tt1517268: {
    imdbID: "tt1517268",
    Title: "Barbie",
    Released: "2023-07-21",
    Runtime: 114,
    Genres: ["Adventure", "Comedy", "Fantasy"],
    Directors: ["Greta Gerwig"],
    Writers: ["Greta Gerwig", "Noah Baumbach"],
    Actors: ["Margot Robbie", "Ryan Gosling", "America Ferrera"],
    Plot: "Barbie erleidet eine Existenzkrise und muss die echte Welt besuchen, um zu verstehen, wer sie wirklich ist.",
    Poster: "/images/barbie.jfif",
    Metascore: 80,
    imdbRating: 6.9,
  },
  tt9362722: {
    imdbID: "tt9362722",
    Title: "Spider-Man: Across the Spider-Verse",
    Released: "2023-06-02",
    Runtime: 140,
    Genres: ["Animation", "Action", "Adventure"],
    Directors: ["Joaquim Dos Santos", "Kemp Powers"],
    Writers: ["Phil Lord", "Christopher Miller"],
    Actors: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    Plot: "Miles Morales katapultiert sich quer durch das Multiversum und trifft auf ein Team von Spider-People.",
    Poster: "/images/spiderman across the universe.jpg",
    Metascore: 86,
    imdbRating: 8.6,
  },
  tt1745960: {
    imdbID: "tt1745960",
    Title: "Top Gun: Maverick",
    Released: "2022-05-27",
    Runtime: 130,
    Genres: ["Action", "Drama"],
    Directors: ["Joseph Kosinski"],
    Writers: ["Ehren Kruger", "Eric Warren Singer"],
    Actors: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
    Plot: "Nach mehr als 30 Jahren im Dienst muss Pete Mitchell eine neue Gruppe von Top-Gun-Absolventen trainieren.",
    Poster: "/images/top gun maverick.jpg",
    Metascore: 78,
    imdbRating: 8.3,
  },
  tt4154796: {
    imdbID: "tt4154796",
    Title: "Avengers: Endgame",
    Released: "2019-04-26",
    Runtime: 181,
    Genres: ["Action", "Adventure", "Drama"],
    Directors: ["Anthony Russo", "Joe Russo"],
    Writers: ["Christopher Markus", "Stephen McFeely"],
    Actors: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    Plot: "Nach den verheerenden Ereignissen von Infinity War formieren sich die Avengers neu, um Thanos' Taten rückgängig zu machen.",
    Poster: "/images/avangers endgame.jpg",
    Metascore: 78,
    imdbRating: 8.4,
  },
  tt1877830: {
    imdbID: "tt1877830",
    Title: "The Batman",
    Released: "2022-03-04",
    Runtime: 176,
    Genres: ["Action", "Crime", "Drama"],
    Directors: ["Matt Reeves"],
    Writers: ["Matt Reeves", "Peter Craig"],
    Actors: ["Robert Pattinson", "Zoë Kravitz", "Jeffrey Wright"],
    Plot: "Als der Riddler eine Mordserie an Gothams Elite beginnt, muss Batman die dunklen Geheimnisse der Stadt lüften.",
    Poster: "/images/the batman.jpg",
    Metascore: 72,
    imdbRating: 7.8,
  },
  tt10366206: {
    imdbID: "tt10366206",
    Title: "John Wick: Chapter 4",
    Released: "2023-03-24",
    Runtime: 169,
    Genres: ["Action", "Crime", "Thriller"],
    Directors: ["Chad Stahelski"],
    Writers: ["Shay Hatten", "Michael Finch"],
    Actors: ["Keanu Reeves", "Laurence Fishburne", "George Jovanovic"],
    Plot: "John Wick deckt einen Weg auf, um die Hohe Kammer zu besiegen, muss sich aber neuen und alten Feinden stellen.",
    Poster: "/images/john wick 4.webp",
    Metascore: 78,
    imdbRating: 7.7,
  },
  tt6710474: {
    imdbID: "tt6710474",
    Title: "Everything Everywhere All at Once",
    Released: "2022-03-25",
    Runtime: 139,
    Genres: ["Action", "Adventure", "Comedy"],
    Directors: ["Daniel Kwan", "Daniel Scheinert"],
    Writers: ["Daniel Kwan", "Daniel Scheinert"],
    Actors: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"],
    Plot: "Eine alternde chinesische Einwandererin wird in ein verrücktes Abenteuer verwickelt, um die Welt zu retten.",
    Poster: "/images/everything everywhere.jpg",
    Metascore: 81,
    imdbRating: 7.8,
  },
  tt1630029: {
    imdbID: "tt1630029",
    Title: "Avatar: The Way of Water",
    Released: "2022-12-16",
    Runtime: 192,
    Genres: ["Action", "Adventure", "Fantasy"],
    Directors: ["James Cameron"],
    Writers: ["James Cameron", "Rick Jaffa"],
    Actors: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    Plot: "Jake Sully und Neytiri gründen eine Familie auf Pandora, müssen aber fliehen, als eine alte Bedrohung zurückkehrt.",
    Poster: "/images/avatar 2.jpg",
    Metascore: 67,
    imdbRating: 7.6,
  }
};